    version: '3.3'

    services:
      api:
        build: .
        volumes:
          - ./:/var/www/html/
        ports:
          - "3030:80"
        environment:
          - S3_ACCESS_KEY_ID
          - S3_SECRET_ACCESS_KEY